# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: NeXDM.NeXDM
PackageVersion: 1.1.3
PackageLocale: en-US
Publisher: NeXDM Software
PublisherUrl: https://nexdm.in
PublisherSupportUrl: https://nexdm.in
PrivacyUrl: https://nexdm.in/privacy
Author: NeXDM Team
PackageName: NeXDM
PackageUrl: https://nexdm.in
License: Freeware
Copyright: Copyright (c) 2026 NeXDM Software
ShortDescription: Ultra-lightweight (4MB) 64-segment download manager built in Rust for high-speed multi-threaded downloads.
Description: |-
  NeXDM is a next-generation, high-performance download accelerator engineered in Rust and Tauri for maximum throughput and minimal system footprint.
  Featuring an ultra-lean 4MB installer, NeXDM splits large files into up to 64 simultaneous parallel segments, saturating your internet bandwidth to deliver up to 10x faster download speeds.
Moniker: nexdm
Tags:
- download-manager
- accelerator
- multi-threaded
- fast-download
- open-source
- utility
ManifestType: defaultLocale
ManifestVersion: 1.6.0
